/**
 * CRDT-compatible conflict types for scoped household state.
 *
 * These types define the collaborative data structures used with Automerge CRDTs
 * for family-web local-first sync. Only the in-scope data types are represented here.
 *
 * Out-of-scope: work memory, site-control state, personal memory across devices.
 *
 * Reference: docs/architecture/local-first-sync-strategy.md | ADR-035
 */

// ── Shopping List ──────────────────────────────────────────────────────────────

export interface ShoppingItem {
  /** Stable item identifier (UUIDv4) */
  id: string;
  /** Display name */
  name: string;
  /** Optional quantity string (e.g., "2 lbs", "1 dozen") */
  quantity?: string;
  /** Store section hint for routing */
  section?: string;
  /** Whether the item has been picked up */
  checked: boolean;
  /** ISO timestamp of last explicit user modification */
  last_modified_at: string;
  /** User who last explicitly modified this item */
  last_modified_by: string;
  /** Whether this item was auto-generated (system suggestion loses to any human edit) */
  auto_generated: boolean;
}

/** Shopping list document: keyed by item ID for Automerge map semantics */
export type ShoppingListDoc = {
  version: number;
  household_id: string;
  items: Record<string, ShoppingItem>;
  last_cleared_at?: string;
};

// ── Chore Assignments ─────────────────────────────────────────────────────────

export interface ChoreAssignment {
  id: string;
  chore_name: string;
  assignee_id: string;
  assignee_name: string;
  due_date: string;             // ISO date (YYYY-MM-DD)
  completed: boolean;
  completed_at?: string;
  /** Rotation index for recurring chores; used by chores.balance_load */
  rotation_index?: number;
  last_modified_by: string;
  last_modified_at: string;
}

export type ChoreAssignmentsDoc = {
  version: number;
  household_id: string;
  assignments: ChoreAssignment[];
  last_rebalanced_at?: string;
};

// ── Conflict Resolution ───────────────────────────────────────────────────────

/**
 * When two concurrent edits to the same field conflict in Automerge merge:
 * - ExplicitUserEdit beats AutoGeneratedSuggestion
 * - ExplicitUserEdit beats ExplicitUserEdit via last-write-wins within Automerge
 * - ExplicitDelete beats any concurrent Add (user intent wins)
 */
export type EditSource = "user_explicit" | "system_suggestion" | "import";

export interface EditMetadata {
  source: EditSource;
  user_id: string;
  timestamp: string;
}

/**
 * Conflict record: written when Automerge detects a concurrent edit that
 * required resolution. Surfaced in the household dashboard for awareness.
 */
export interface ConflictRecord {
  id: string;
  resource_type: "shopping_item" | "chore_assignment";
  resource_id: string;
  field: string;
  winning_value: unknown;
  losing_value: unknown;
  winning_edit: EditMetadata;
  losing_edit: EditMetadata;
  resolution_rule: "explicit_beats_auto" | "last_write_wins" | "explicit_delete_wins";
  resolved_at: string;
}

// ── PGlite Cache Schema Types ─────────────────────────────────────────────────

/** Reminder cache entry — read-only offline; synced from server on reconnect */
export interface ReminderCacheEntry {
  id: string;
  title: string;
  due_at: string;
  scope: "PERSONAL" | "HOUSEHOLD_SHARED";
  status: "ACTIVE" | "SNOOZED" | "COMPLETED";
  cached_at: string;
}

/** Approval cache entry — read-only offline; cannot be approved offline */
export interface ApprovalCacheEntry {
  id: string;
  type: string;
  description: string;
  requester_id: string;
  expires_at: string;
  status: "PENDING" | "APPROVED" | "DENIED";
  cached_at: string;
  /** Approval requires approval-track auth; never available offline */
  readonly approval_requires_network: true;
}

/** Dashboard snapshot — stale-while-revalidate; invalidated on reconnect */
export interface DashboardSnapshot {
  snapshot_id: string;
  household_id: string;
  snapshot_at: string;
  active_chores_count: number;
  pending_approvals_count: number;
  shopping_items_count: number;
  energy_kwh_today?: number;
  alerts: Array<{ type: string; message: string; severity: "info" | "warning" | "error" }>;
}

// ── Sync State ────────────────────────────────────────────────────────────────

export interface SyncState {
  last_synced_at: string | null;
  is_online: boolean;
  pending_changes: number;
  sync_error: string | null;
}
