#!/usr/bin/env python3
"""
Generate docs/README.md — auto-indexed documentation map for the Computer monorepo.

Run:
    python3 scripts/generate_docs_index.py

Output:
    docs/README.md
"""

from __future__ import annotations

import os
import re
from pathlib import Path

ROOT = Path(__file__).parent.parent
DOCS_DIR = ROOT / "docs"
OUTPUT = DOCS_DIR / "README.md"


def get_title(path: Path) -> str:
    """Extract first H1 or H2 heading from a markdown file."""
    try:
        with open(path) as f:
            for line in f:
                line = line.strip()
                if line.startswith("# "):
                    return line[2:].strip()
                if line.startswith("## "):
                    return line[3:].strip()
    except Exception:
        pass
    return path.stem.replace("-", " ").title()


def get_summary(path: Path) -> str:
    """Extract the first blockquote summary line."""
    try:
        with open(path) as f:
            content = f.read()
            match = re.search(r"^>\s*(.+)$", content, re.MULTILINE)
            if match:
                return match.group(1).strip()
    except Exception:
        pass
    return ""


def collect_docs(subdir: str, label: str) -> list[tuple[str, str, str]]:
    """Collect (rel_path, title, summary) for all .md files in a subdir."""
    target = DOCS_DIR / subdir
    if not target.exists():
        return []
    entries = []
    for path in sorted(target.glob("*.md")):
        if path.name == "README.md":
            continue
        rel = f"docs/{subdir}/{path.name}"
        title = get_title(path)
        summary = get_summary(path)
        entries.append((rel, title, summary))
    return entries


def render_table(entries: list[tuple[str, str, str]], root: Path) -> str:
    if not entries:
        return "_None yet._\n"
    lines = ["| Document | Summary |", "|----------|---------|"]
    for rel, title, summary in entries:
        link = f"[{title}]({rel})"
        lines.append(f"| {link} | {summary[:80] + '…' if len(summary) > 80 else summary} |")
    return "\n".join(lines) + "\n"


def main() -> None:
    arch_entries = collect_docs("architecture", "Architecture")
    adr_entries = collect_docs("adr", "ADRs")
    product_entries = collect_docs("product", "Product")
    safety_entries = collect_docs("safety", "Safety")
    delivery_entries = collect_docs("delivery", "Delivery")
    runbook_entries: list = []  # placeholder

    content = f"""# Documentation Index

> Auto-generated index of all documentation in the Computer monorepo. Run `python3 scripts/generate_docs_index.py` to refresh.

---

## Architecture

{render_table(arch_entries, ROOT)}

---

## Architectural Decision Records (ADRs)

{render_table(adr_entries, ROOT)}

---

## Product

{render_table(product_entries, ROOT)}

---

## Safety

{render_table(safety_entries, ROOT)}

---

## Delivery

{render_table(delivery_entries, ROOT)}

---

## Runbooks

{render_table(runbook_entries, ROOT)}

---

## Standards and Templates

| Document | Description |
|----------|-------------|
| [documentation-style-guide.md](standards/documentation-style-guide.md) | Tone, heading hierarchy, diagrams, tables, length limits |
| [README.template.md](templates/README.template.md) | Canonical README template for services and packages |

---

## CLI Reference

See [docs/cli/command-reference.md](cli/command-reference.md) for all `computer` CLI commands, Taskfile tasks, and scenario scripts.

---

_Generated by `scripts/generate_docs_index.py`_
"""

    OUTPUT.write_text(content)
    print(f"Written: {OUTPUT}")


if __name__ == "__main__":
    main()
